### ISSUE TITLE
最新内容 pdf 目录生成页面偏差大

### ISSUE THREAD

**Issue by ehlxr** [me1ting/trpl-zh-cn-pdf#1]
大神你好，https://kaisery.github.io/trpl-zh-cn 的最新内容按您的方法生成的 bookmarks.txt 页码偏差特别大，使用 bookmarks-fixer 修复全是「no result of `xxxxx`, please fix it by hand」

**Comment by me1ting** [comment]
代码没啥问题，你没通过油猴脚本生成书签吧。

已发布最新版本。
